### ISSUE TITLE
Nextcloud 10 times out when trying to use API

### ISSUE THREAD

**Issue by tapir** [fcturner/passwords#255]
The app works successfully from the web interface but firefox addon times out. I tried doing this
```curl -u myuser https://myseerver.com/index.php/apps/passwords/api/0.1/version
Enter host password for user 'myuser':```
And the result was:
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>
```

**Comment by fcturner** [comment]
Well, that must be NextCloud related or related to the Firefox plugin. I'm not the author of that plugin. It works fine on ownCloud 9.1.0 however. You could contact https://github.com/eglia.

**Comment by tapir** [comment]
It's not extension related because as I mentioned it times out with curl as well.
It might be nextcloud related but it might also be related to this app's API routing or something

**Comment by fcturner** [comment]
That's true. This apps routing seems ok, because as I mentioned it works on ownCloud. So definitely NextCloud related.
I will look into this.

**Comment by fcturner** [comment]
Can you try this on another machine to exclude you system as possible show stopper?

**Comment by tapir** [comment]
I will do that in the mean time here are some errors from the Nextclodu log that might be related or not. I have these errors multiple times in the log.
```json
{
   "reqId":"6jOwuPonng\/u9d4yMT4B",
   "remoteAddr":"x.x.x.x",
   "app":"PHP",
   "message":"Uninitialized string offset: 0 at \/var\/www\/nextcloud\/apps\/passwords\/service\/passwordservice.php#360",
   "level":3,
   "time":"2016-09-05T17:48:38+00:00",
   "method":"POST",
   "url":"\/index.php\/apps\/passwords\/api\/0.1\/passwords",
   "user":"myuser"
}
{
   "reqId":"Fwin3eH\/enbj2Lgwqp\/3",
   "remoteAddr":"x.x.x.x",
   "app":"PHP",
   "message":"Undefined index: PHP_AUTH_USER at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Middleware\/Security\/CORSMiddleware.php#88",
   "level":3,
   "time":"2016-09-05T20:01:52+00:00",
   "method":"GET",
   "url":"\/index.php\/apps\/passwords\/api\/0.1\/version",
   "user":"myuser"
}
{
   "reqId":"Fwin3eH\/enbj2Lgwqp\/3",
   "remoteAddr":"85.106.41.149",
   "app":"no app in context",
   "message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"key uid is expected to be set in $param\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OC\\\\User\\\\Database::preLoginNameUsedAsUserName(Array)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Util.php(489): OC_Hook::emit('\\\\\\\\OCA\\\\\\\\Files_Shar...', 'preLoginNameUse...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(363): OCP\\\\Util::emitHook('\\\\\\\\OCA\\\\\\\\Files_Shar...', 'preLoginNameUse...', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(321): OC\\\\User\\\\Session->isTwoFactorEnforced(NULL)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/Security\\\/CORSMiddleware.php(93): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/MiddlewareDispatcher.php(94): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\Passwords\\\\Controller\\\\VersionApiController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\Passwords\\\\Controller\\\\VersionApiController), 'index')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(111): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passwords\\\\Controller\\\\VersionApiController), 'index')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Passwords\\\\\\\\C...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(967): OC\\\\Route\\\\Router->match('\\\/apps\\\/passwords...')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Database.php\",\"Line\":341}",
   "level":3,
   "time":"2016-09-05T20:02:22+00:00",
   "method":"GET",
   "url":"\/index.php\/apps\/passwords\/api\/0.1\/version",
   "user":"--"
}
{
   "reqId":"Fwin3eH\/enbj2Lgwqp\/3",
   "remoteAddr":"x.x.x.x",
   "app":"PHP",
   "message":"Undefined index: PHP_AUTH_PW at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Middleware\/Security\/CORSMiddleware.php#89",
   "level":3,
   "time":"2016-09-05T20:01:52+00:00",
   "method":"GET",
   "url":"\/index.php\/apps\/passwords\/api\/0.1\/version",
   "user":"myuser"
}
```

**Comment by fcturner** [comment]
This one:
`Undefined index: PHP_AUTH_USER at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Middleware\/Security\/CORSMiddleware.php#88`

And this one:
`Undefined index: PHP_AUTH_PW at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Middleware\/Security\/CORSMiddleware.php#89`

make it hard to debug since I don't use NextCloud and they (just like ownCloud) never keep developers up to date about changes they make in their scripts. Almost impossible to keep up for app developers, of which this error is a fantastic example. 

I'm thinking, eventually app developers need to choose between ownCloud or NextCloud, as NextCloud is undoubtedly wanting to get as far away from ownCloud as possible. Might be that they started this journey already on API's. I'll see what I can do by looking into scripts of core NextCloud apps.

**Comment by tapir** [comment]
You're very right. Some developers really don't get the importance of a stable API.
Best of luck figuring it out. Let me know if I can help

**Comment by fcturner** [comment]
Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)). I cannot reproduce this.

I have ownCloud and NextCloud installed on the same server (different subdomains). It works perfectly here (PHP 7, Apache, Linux). 
However, the url for ownCloud (9.1) is
`https://sub1.website.com/apps/passwords/api/0.1/version`
and for NextCloud (10)
`https://sub2.website.com/index.php/apps/passwords/api/0.1/version`

But you already tried with `/index.php/`, so that won't help you. Please check if this problem still exists on NC 10.

**Comment by fcturner** [comment]
Tried with `curl` too, btw.

**Comment by iudex-** [comment]
Hey
I'm running Nextcloud 10 on NGINX with APCu enabled and am running into this problem too.
I increased the php and nginx timeouts to 120 seconds, now API request work but take on avg 60 seconds...

It is reproducible in curl and browser plugins.

Maybe it is related to authenification? Request with an invalid password take equally long
`time curl -i -X GET https://test:wrongpassword@wolke.endlevel.de/index.php/apps/passwords/api/0.1/passwords
`

If I can help in any way to debug this please tell me :)

**Comment by fcturner** [comment]
Yes, NextCloud must have changed something to their API structure. I still can't find it. How annoying!!

**Comment by fcturner** [comment]
@tapir are you using NGINX too?

**Comment by tapir** [comment]
yes nginx ahd php-fpm
