### ISSUE TITLE
Call to undefined function OCA\\Passwords\\Service\\mcrypt_get_iv_size

### ISSUE THREAD

**Issue by Happyfeet01** [fcturner/passwords#295]
Hello,

i got this Error message for the Passwords App.

Version: v19
Nextcloud: 10.0.1
Ubuntu 16.04 LTS
Apache2
Nginx as reverse Proxy
PHP 7.0.13

i use Version 19 because i use the Android App to show my Passwords on mobile Device. The android App is currently not compatible with the latest beta Version. https://github.com/intirix/cloudpasswordmanager

````
Exception: {"Exception":"Error","Message":"Call to undefined function OCA\\Passwords\\Service\\mcrypt_get_iv_size()","Code":0,"Trace":"#0 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/service\/passwordservice.php(478): OCA\\Passwords\\Service\\Encryption->getKeys('', '9a9c20655387b40...')\n#1 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/service\/passwordservice.php(43): OCA\\Passwords\\Service\\Encryption->decrypt(*** sensitive parameters replaced ***)\n#2 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/controller\/passwordcontroller.php(27): OCA\\Passwords\\Service\\PasswordService->findAll('lars')\n#3 [internal function]: OCA\\Passwords\\Controller\\PasswordController->index()\n#4 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#5 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Passwords\\Controller\\PasswordController), 'index')\n#6 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Passwords\\Controller\\PasswordController), 'index')\n#7 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Passwords\\\\C...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#9 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#10 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/passwords...')\n#11 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/index.php(48): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/service\/passwordservice.php","Line":529}  2016-11-24T21:46:58+01:00  lars 
Error  PHP  Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#41  2016-11-24T21:46:58+01:00  lars 
Error  PHP  Use of undefined constant MCRYPT_BLOWFISH - assumed 'MCRYPT_BLOWFISH' at /var/www/vhosts/land-laeufer.de/cloud.land-laeufer.de/nextcloud/apps/passwords/service/passwordservice.php#41  2016-11-24T21:46:58+01:00  lars 
Error  index  Exception: {"Exception":"Error","Message":"Call to undefined function OCA\\Passwords\\Service\\mcrypt_get_iv_size()","Code":0,"Trace":"#0 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/service\/passwordservice.php(478): OCA\\Passwords\\Service\\Encryption->getKeys('', '9a9c20655387b40...')\n#1 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/service\/passwordservice.php(43): OCA\\Passwords\\Service\\Encryption->decrypt(*** sensitive parameters replaced ***)\n#2 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/controller\/passwordapicontroller.php(35): OCA\\Passwords\\Service\\PasswordService->findAll('lars')\n#3 [internal function]: OCA\\Passwords\\Controller\\PasswordApiController->index()\n#4 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#5 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Passwords\\Controller\\PasswordApiController), 'index')\n#6 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Passwords\\Controller\\PasswordApiController), 'index')\n#7 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Passwords\\\\C...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#9 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#10 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/passwords...')\n#11 \/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/index.php(48): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/vhosts\/land-laeufer.de\/cloud.land-laeufer.de\/nextcloud\/apps\/passwords\/service\/passwordservice.php","Line":529}  
```

**Comment by fcturner** [comment]
You need to have the mcrypt package installed. It's a dependency set in one of the app files (appinfo/info.xml) and installation should've been blocked since mcrypt is missing apparently.

I really don't get NextCloud. It far much work to support and seems more fussy than ownCloud. 

According to https://launchpad.net/ubuntu/+source/php7.0, the package for mcrypt is called php7.0-mcrypt if you're on PHP 7. So just 'sudo apt-get install php7.0-mcrypt' and you should be fine.

**Comment by fcturner** [comment]
I guess this can be closed. Please let me know if anything is still wrong.
